### ISSUE TITLE
GO vulnerability 

### ISSUE THREAD

**Issue by rahools** [wso2/streaming-integrator#266]
**Description:**
JFrog Xray scan gives out various GO vuln.

**Suggested Labels:**
security

**Affected Product Version:**
4.1.0-rc2

**Comment by AnuGayan** [comment]
Hi @rahools 

Could you please share the security report with WSO2 (who is maintaining the Streaming Integrator product) as mentioned below?
 
Important: Please be advised that security issues must be reported to [security@wso2.com](mailto:security@wso2.com), not as GitHub issues, in order to reach the proper audience. We strongly advise following the [WSO2 Security Vulnerability Reporting Guidelines](https://docs.wso2.com/display/Security/WSO2+Security+Vulnerability+Reporting+Guidelines) when reporting security issues.
